openapi: 3.0.0
info:
  title: TodoApi
  description: A simple to-do list
  version: 1.0.0
servers:
  - url: https://c056-2601-204-e782-f580-918a-534a-7410-67b3.ngrok-free.app
    description: The todo api server
paths:
  /api/TodoItems:
    get:
      tags:
        - TodoItems
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'

  /api/TodoItems/{id}:
    get:
      tags:
        - TodoItems
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TodoItem'
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
            text/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
components:
  schemas:
    TodoItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        isComplete:
          type: boolean
      additionalProperties: false
